---
title: "Assignment 3"
author: "Zeming Liang"
date: "2020/12/10"
output:
  html_document:
    df_print: paged
---


```{r}
library(mice)
load("/cloud/project/NHANES2.Rdata")
load("/cloud/project/dataex2.Rdata")
load("/cloud/project/dataex4.Rdata")
```

## Q1

### 1a

```{r 1a}
#View(nhanes)
n <- nrow(nhanes)
# Calculate NA percentage
mis <- ifelse(complete.cases(nhanes)==FALSE, 1, 0)
missing_percent <- sum(mis) / n
missing_percent
```

### 1b

```{r 1b}
imps <- mice(nhanes, seed=1, printFlag=FALSE)
fits <- with(imps, lm(bmi ~ age + hyp + chl))
bmi_ests = pool(fits)$pooled[c(1, 3, 10)]
bmi_ests
```

### 1c

```{r 1c}
results <- bmi_ests
for (i in 1:6) {
  imps <- mice(nhanes, seed=i, printFlag=FALSE)
  fits <- with(imps, lm(bmi ~ age + hyp + chl))
  bmi_ests = pool(fits)$pooled[c(1, 3, 10)]
  results[i,] <- bmi_ests[which(bmi_ests$lambda==max(bmi_ests$lambda)),]
}
results
```

### 1d

```{r 1d}
results <- bmi_ests
for (i in 1:6) {
  imps <- mice(nhanes, seed=i, m=100, printFlag=FALSE)
  fits <- with(imps, lm(bmi ~ age + hyp + chl))
  bmi_ests = pool(fits)$pooled[c(1, 3, 10)]
  results[i,] <- bmi_ests[which(bmi_ests$lambda==max(bmi_ests$lambda)),]
}
results
```

## Q2

```{r 2}
#dim(dataex2)

# calculate the empirical coverage probability
sri_num = 0
boot_num = 0
# Imputations begin...
for (i in 1:100){
  #SRI method
  imps_sri <- mice(dataex2[,,i], m=20, seed=1, printFlag=FALSE, method="norm.nob")
  ests_sri <- summary(pool(with(imps_sri, lm(Y ~ X))), conf.int = TRUE)
  sri_ci <- ests_sri[2,c(7,8)]

  #bootstrap method
  imps_boot <- mice(dataex2[,,i], m=20, seed=1, printFlag=FALSE, method="norm.boot")
  ests_boot <- summary(pool(with(imps_boot, lm(Y ~ X))), conf.int=TRUE)
  boot_ci <- ests_boot[2,c(7,8)]
  
  #check if the interval contains the true value of the parameter beta1
  if (sri_ci[1] <= 3 & sri_ci[2] >= 3){
    sri_num = sri_num+1
  }  
  if (boot_ci[1] <= 3 & boot_ci[2] >= 3){
    boot_num = boot_num+1
  }
}

emp_cov_prob <- data.frame(sri_prob=sri_num/100,boot_prob=boot_num/100)
emp_cov_prob

```


## Q4

### 4a

```{r 4a}
imps_4a <- mice(dataex4, m=50, seed=1, printFlag=FALSE)
ests_4a <- with(imps_4a, lm(y ~ x1 + x2 + x1*x2))
summary(pool(ests_4a), conf.int=TRUE)[c(1,2,7,8)]
```

### 4b

```{r 4b}
#calculate the interaction variable and append it to data set
dataex4$x1x2 <- dataex4$x1 * dataex4$x2
imps_0 <- mice(dataex4, maxit=0, m=50, seed=1, printFlag=FALSE)
#passive imputation strategy by specifying a formula to calculate x1x2
meth <- imps_0$method
meth["x1x2"] <- "~I(x1*x2)"
#x1x2 will not be used as predictor of x1 and x2
pred <- imps_0$predictorMatrix
pred[c("x1", "x2"), "x1x2"] <- 0
pred["x1x2","y"] <- 0
#ensure visit sequence
imps_0$visitSequence
#adjusted imputation
imps_4b <- mice(dataex4, maxit = 20, method=meth, predictorMatrix=pred,m=50, seed=1, printFlag=FALSE)
imps_4b$loggedEvents
ests_4b <- with(imps_4b, lm(y ~ x1 + x2 + x1x2))
summary(pool(ests_4b), conf.int=TRUE)[c(1,2,7,8)]
```


### 4c

```{r 4c}
imps_4c <- mice(dataex4, m=50, maxit = 20, seed=1, printFlag=FALSE)
ests_4c <- with(imps_4c, lm(y ~ x1 + x2 + x1x2))
summary(pool(ests_4c), conf.int=TRUE)[c(1,2,7,8)]
```

## Q5

```{r 5, warning=FALSE}
str(NHANES2)
NHANES2$SBP[is.nan(NHANES2$SBP)] <- NA
summary(NHANES2)
require(JointAI)
md_pattern(NHANES2, pattern = FALSE, color = c('#34111b', '#e30f41'))
par(mar = c(3, 3, 2, 1), mgp = c(2, 0.6, 0))
plot_all(NHANES2, breaks = 30, ncol = 4)
imp <- mice(NHANES2, maxit = 20, m = 30, seed = 1, printFlag = FALSE)
imp$loggedEvents
```

```{r check}
plot(imp,layout = c(4,4))
densityplot(imp)
densityplot(imp, ~hgt|gender)
densityplot(imp, ~SBP|hypten + gender)
densityplot(imp, ~WC|gender)
require(devtools)
require(reshape2)
require(RColorBrewer)
require(ggplot2)
source_url("https://gist.githubusercontent.com/NErler/0d00375da460dd33839b98faeee2fdab/raw/c6f537ecf80eddcefd94992ec7926aa57d454536/propplot.R")
propplot(imp)
xyplot(imp, WC ~ hgt | gender, pch = c(1, 20))
```


```{r impute}
fit <- with(imp, lm(wgt ~ gender + age + hgt + WC))
summary(fit$analyses[[1]])
```



```{r check2}
comp1 <- complete(imp, 1)
plot(fit$analyses[[1]]$fitted.values, residuals(fit$analyses[[1]]),
xlab = "Fitted values", ylab = "Residuals")
par(mfrow = c(2, 2))
plot(comp1$wgt ~ comp1$age, xlab = "Age", ylab = "wgt")
plot(comp1$wgt ~ comp1$hgt, xlab = "hgt", ylab = "wgt")
plot(comp1$wgt ~ comp1$WC, xlab = "WC", ylab = "wgt")
boxplot(comp1$wgt ~ comp1$gender, xlab = "gender", ylab = "wgt")
qqnorm(rstandard(fit$analyses[[1]]), xlim = c(-4, 4), ylim = c(-6, 6))
qqline(rstandard(fit$analyses[[1]]), col = 2)
```


```{r pool}
pooled_ests <- pool(fit)
summary(pooled_ests, conf.int = TRUE)
pool.r.squared(pooled_ests, adjusted = TRUE)
```



```{r compare}
fit_no_gender <- with(imp, lm(wgt ~ age + hgt + WC))
D1(fit, fit_no_gender)
fit_no_age <- with(imp, lm(wgt ~ gender + hgt + WC))
D1(fit, fit_no_age)
fit_no_hgt <- with(imp, lm(wgt ~ gender + age + WC))
D1(fit, fit_no_hgt)
fit_no_WC <- with(imp, lm(wgt ~ gender + age + hgt))
D1(fit, fit_no_WC)
```